---
- name: Restart livekit
  command: docker compose -f {{ docker_compose_dir }}/livekit/docker-compose.yml restart livekit

- name: Restart lk-jwt
  command: docker compose -f {{ docker_compose_dir }}/livekit/docker-compose.yml restart lk-jwt
