---
livekit_version: "1.8.2"
livekit_jwt_version: "latest"
livekit_config_dir: "/etc/livekit"
livekit_log_dir:    "/var/log/livekit"

# Регион WebRTC (для ICE candidates)
livekit_rtc_use_external_ip: true

# Лимиты
livekit_limit_num_tracks: 0           # 0 = без лимита
livekit_limit_bytes_per_sec: 0        # 0 = без лимита
