---
# Переменные с дефолтами; переопределяются в host_vars/haproxy01
haproxy_maxconn:  50000
haproxy_nbthread: 4
haproxy_stats_port: 8404
haproxy_stats_user: "hapadmin"
haproxy_stats_password: "changeme"
haproxy_timeout_connect: "5s"
haproxy_timeout_client:  "120s"
haproxy_timeout_server:  "120s"
haproxy_timeout_tunnel:  "3600s"
haproxy_timeout_http_req: "10s"
haproxy_timeout_queue:   "30s"
